### ISSUE TITLE
where do we find vls-128.engine https://github.com/tier4/AutowareArchitectureProposal/tree/master/src/perception/object_recognition/detection/lidar_apollo_instance_segmentation?

### ISSUE THREAD

**Issue by chowkamlee81** [kosuke55/train_baiducnn#11]
I was trying to run lidar_apollo_instance_segmentation. But iam not able to find vls-128.engine? Kindly please help, do the needful

**Comment by kosuke55** [comment]
@chowkamlee81 
You can build and run  lidar_apollo_instance_segmentation and it will automatically generate an engine.

**Comment by chowkamlee81** [comment]
Thanks closing the issue
