### ISSUE TITLE
Inference on kitti dataset

### ISSUE THREAD

**Issue by chowkamlee81** [kosuke55/train_baiducnn#12]
I used kitti bag file from "http://robotics.ethz.ch/~asl-datasets/segmap/segmap_data/kitti/2011_10_03_drive_27.bag" , build entire package  , changed input topics name with lidar_apollo_instance_segmentation
https://github.com/tier4/AutowareArchitectureProposal/tree/master/src/perception/object_recognition/detection/lidar_apollo_instance_segmentation.

Module works only fine with the bag file that you have used.
With kitti bag files, Output results are nil and not able to detect anything. 

I used hdl-64.caffemodel and hdl-64.prototxt and tensorrt engine developed from code automotically. Kindly help .

**Comment by kosuke55** [comment]
@chowkamlee81 
Any rosbag can be used as long as the type is PointClound2.
Check if the object is not recognized, or if the topic is not published, or if you use a rostopic hz.

**Comment by chowkamlee81** [comment]
I replaced the subscriber topic with "/velodyne_points" at line 
https://github.com/tier4/AutowareArchitectureProposal/blob/master/src/perception/object_recognition/detection/lidar_apollo_instance_segmentation/src/node.cpp#L24
Even though many vehicles/cars were there in that bag but none are getting detected. 
Iam using hdl-64.prototxt and hdl-64.caffemodel since kitti belong velodyne-64.
Moreover kitti bag has topic "velodyne_points" which belongs to sensoR_msgs::PointCloud2 type.

Kindly help

Kindly help

**Comment by kosuke55** [comment]
@chowkamlee81 
Please change the input topic of the launch instead of cpp.
https://github.com/tier4/AutowareArchitectureProposal/blob/7bcd295c33e989786c7a7c14a718d8ee9bd3c0b9/src/perception/object_recognition/detection/lidar_apollo_instance_segmentation/launch/lidar_apollo_instance_segmentation.launch#L18

**Comment by muzi2045** [comment]
If you are using this repo code to train a new model.
notice one place in tensorrt inference code:

```
void FeatureMap::resetMap(std::vector<float> & map)
{
  const int size = width * height;
  for (int i = 0; i < size; ++i) {
    max_height_data[i] = -5.0f; /// the max_height_data[i] should be zero.
    mean_height_data[i] = 0.0f;
    count_data[i] = 0.0f;
    nonempty_data[i] = 0.0f;
  }
}
```

**Comment by chowkamlee81** [comment]
I remaped from "/sensing/lidar/top/rectified/pointcloud" to "/velodyne_points" in the code https://github.com/tier4/AutowareArchitectureProposal/blob/7bcd295c33e989786c7a7c14a718d8ee9bd3c0b9/src/perception/object_recognition/detection/lidar_apollo_instance_segmentation/launch/lidar_apollo_instance_segmentation.launch#L18

Results remain same with none of the objects are getting detected. Hence kindly help.

**Comment by kosuke55** [comment]
I've downloaded and tried your rosbag, just change the topic name of the launch and it will work fine.
If you have changed the source code, please restore the source code and rebuild it.
![Screenshot from 2020-05-30 16-31-21](https://user-images.githubusercontent.com/39142679/83322484-0e2ddb80-a293-11ea-9860-00dc180289df.png)

**Comment by chowkamlee81** [comment]
Thanks @kosuke55 I will again cross check and verify the results

**Comment by chowkamlee81** [comment]
Worked well with your suggestion. Thanks closing issue
